### ISSUE TITLE
Streaming is very slow

### ISSUE THREAD

**Issue by sandesha-hegde** [jeffbass/imagezmq#61]
Hi Jeff,

Love your project. I ran the sender and receiver scripts which are mentioned in the README file `test_1_receive_images.py` and `test_1_send_images.py` but I'm facing lot of delay while sending and receiving the frames.

SYSTEM details:

python: 3.7
OS: Ubuntu 18.04

**Comment by sandesha-hegde** [comment]
Sorry Jeff, I forgot to change the `time.sleep()`

**Comment by jeffbass** [comment]
No worries. Glad you got it fixed.
