### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by mohan51** [jeffbass/imagezmq#81]
Hi Jeff,
I am getting --> if image.flags['C_CONTIGUOUS']:  AttributeError: 'NoneType' object  has no attribute 'flags'
while connected my two raspberrypi's to pc

**Comment by jeffbass** [comment]
I believe we got this problem fixed in your [imagenode issue #23.](https://github.com/jeffbass/imagenode/issues/23) But if you have other questions about imageZMQ, feel free to open an issue in this repository.
